
export interface Structure{

 IDSTRUCTURE:number;
 IDACTIVITY:number;
 STRUCTURENAME :string;
 STRUCTURECODELIKE:string;
STRUCTURECODENOTLIKE:number;
STATUSSTRUCTURE:number;
EMAILGROUPMANAGERS:string;


	
}